### ISSUE TITLE
Develop a collaboration standard

### ISSUE THREAD

**Issue by alecgirman** [alecgirman/PyNodeG#6]
# Develop a Git collaboration standard

- [ ] Create a guideline on creating and completing issues

- [ ] Define a process on reviewing and testing code

- [ ] Plan how milestones and projects will be used

- [ ] Make documentation standards

- [ ] (Optional) Make templates for pull requests and issues

These will all go into the wiki for now
